--TUTORIAL https://www.youtube.com/watch?v=MsEthF78STM
-- CREAR TABLA CLIENTE
CREATE TABLE CLIENTE (
	IDCLI INTEGER NOT NULL,
	NOMCLI VARCHAR2(50) NOT NULL,
	APECLI VARCHAR2(50) NOT NULL,
	DIRCLI VARCHAR2(80) NOT NULL,
    EMACLI VARCHAR2(50) UNIQUE NOT NULL,
    DNICLI CHAR(8) UNIQUE NOT NULL,
	CELCLI CHAR(9) NOT NULL,
	CODUBI CHAR(6) NOT NULL,
	ESTCLI CHAR(1) NOT NULL,
	CONSTRAINT CLIENTE_pk PRIMARY KEY(IDCLI)
);

--SECUANCIA PARA EL ID CLIENTE
CREATE SEQUENCE ID_CLIENTE START WITH 1 INCREMENT BY 1 ORDER;

--TRIGGER PARA EL ID CLIENTE
CREATE OR REPLACE TRIGGER ID_CLIENTE BEFORE INSERT ON CLIENTE FOR EACH ROW BEGIN SELECT ID_CLIENTE.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
END;
/

-- INSERTAR REGISTROS DE CLIENTE
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Juan Gabriel','Condori Jara','Nuevo Hualcara Mz:K Lt:3','juan.condori.jara@vallegrande.edu.pe','45698574','940460321','150501','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Sergio Danilo','Flores Tadeo','San Vicente Mz:J Lt:5','sergio.flores@vallegrande.edu.pe','50398574','948695767','150502','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Josue Miguel','Alarcon Asto','Santa Rosa Mz:T Lt:7','josue@gmail.com','48947854','998475645','150503','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Maria Daniela','Díaz Romero','Imperial Mz:C Lt:9','maria@gmail.com','49589432','903489256','150504','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Diego Alvaro','Galvez Quispe','Las Malvinas Mz:V Lt:2','diego@gmail.com','46087689','919803481','150505','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Lucia Dayana','Cuzcano Cuya','Santa Rosa Mz:E Lt:4','lucia@gmail.com','51289456','989347622','150506','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Victor Raúl','Quispe Manturano','San Luis Mz:G Lt:6','victor@gmail.com','55904785','998143568','150507','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Sofia Carmen','Huamán Vásquez','San Antonio Mz:R Lt:3','sofia@gmail.com','49745632','932457821','150508','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Kevin Rodrigo','Guerra Cáceres','Nuevo Imperial Mz:F Lt:6','kevin@gmail.com','48563483','998436512','150509','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Brayan Enrique','Vicente Manrique','Mala Mz:N Lt:8','brayan@gmail.com','47846370','956734563','150510','A');



--CURSOR EXPLICITO SIMPLE
SET SERVEROUTPUT ON;
DECLARE
    V_DEMO CLIENTE%ROWTYPE;
    CURSOR C_CURSOR IS SELECT * FROM CLIENTE WHERE IDCLI <= 5;
BEGIN
  OPEN C_CURSOR;
  LOOP
    FETCH C_CURSOR INTO V_DEMO;
    EXIT WHEN C_CURSOR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(V_DEMO.NOMCLI || ' ' || V_DEMO.APECLI);
  END LOOP;
  CLOSE C_CURSOR;
END;
/



--CURSOR EXPLICITO CON PARAMETROS
SET SERVEROUTPUT ON;
DECLARE
    --DECLARANDO VARIABLES Y EL CURSOR
    V_NOMBRES CLIENTE.NOMCLI%TYPE;
    V_APELLIDOS CLIENTE.APECLI%TYPE;
    CURSOR C_CLIENTE (V_IDCLI CLIENTE.IDCLI%TYPE)
    IS SELECT NOMCLI, APECLI FROM CLIENTE WHERE IDCLI = V_IDCLI;
BEGIN
  OPEN C_CLIENTE(1);
  LOOP
    FETCH C_CLIENTE INTO V_NOMBRES, V_APELLIDOS;
    EXIT WHEN C_CLIENTE%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NOMBRES: ' || V_NOMBRES || ', APELLIDOS: ' || V_APELLIDOS);
    DBMS_OUTPUT.PUT_LINE('NOMBRES Y APELLIDOS: ' || V_NOMBRES || ' ' || V_APELLIDOS);
  END LOOP;
  CLOSE C_CLIENTE;
END;
/



--CURSOR EXPLICITO CON PARAMETROS
SET SERVEROUTPUT ON;
DECLARE
    --DECLARANDO VARIABLES Y EL CURSOR
    V_NOMBRES CLIENTE.NOMCLI%TYPE;
    V_APELLIDOS CLIENTE.APECLI%TYPE;
    V_DNI CLIENTE.DNICLI%TYPE;
    CURSOR C_CLIENTE (V_IDCLI CLIENTE.IDCLI%TYPE)
    IS SELECT NOMCLI, APECLI, DNICLI FROM CLIENTE WHERE IDCLI = V_IDCLI;
BEGIN
  OPEN C_CLIENTE(1);
  LOOP
    FETCH C_CLIENTE INTO V_NOMBRES, V_APELLIDOS, V_DNI;
    EXIT WHEN C_CLIENTE%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('NOMBRES: ' || V_NOMBRES || ', APELLIDOS: ' || V_APELLIDOS || ', DNI: ' || V_DNI);
    DBMS_OUTPUT.PUT_LINE('NOMBRES Y APELLIDOS: ' || V_NOMBRES || ' ' || V_APELLIDOS  || ', DNI: ' || V_DNI);
  END LOOP;
  CLOSE C_CLIENTE;
END;
/



--CURSOR PARA ACTUALIZAR
SET SERVEROUTPUT ON;
DECLARE
  CURSOR C_CLIENTE IS
  SELECT DNICLI, NOMCLI, APECLI FROM CLIENTE WHERE IDCLI = 5
  FOR UPDATE;
  V_DNI CHAR(8);
  V_NOMBRE VARCHAR2(50);
  V_APELLIDO VARCHAR2(50);
BEGIN
  OPEN C_CLIENTE;
  FETCH C_CLIENTE INTO V_DNI, V_NOMBRE, V_APELLIDO;
  WHILE C_CLIENTE%found
    LOOP
      --UPDATE CLIENTE SET NOMCLI = NOMCLI || 'Carlos'
      --UPDATE CLIENTE SET NOMCLI = 'Ambos Nombres'
      UPDATE CLIENTE SET DNICLI = '70326789'
      WHERE CURRENT OF C_CLIENTE;
      FETCH C_CLIENTE INTO V_DNI, V_NOMBRE, V_APELLIDO;
      DBMS_OUTPUT.PUT_LINE('DNI: ' || V_DNI || '   NOMBRES Y APELLIDOS: ' || V_NOMBRE || ' ' || V_APELLIDO);
    END LOOP;
  CLOSE C_CLIENTE;
  COMMIT;
END;
/

SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE WHERE IDCLI = 5;
